Repository ucb-bar/chipyard, pull requests merged in 2019-07, with the labels that each got.

#136 Allow esp-tools to get updated after init script
  scripts/init-submodules-no-riscv-tools.sh
Labels: bug

#140 remove duplicate blackbox files | general grep
  common.mk
  sims/vsim/Makefile
Labels: bug

#137 Remote CI Builds
  .circleci/README.md
  .circleci/build-toolchains.sh
  .circleci/build-verilator.sh
  .circleci/check-commit.sh
  .circleci/clean-old-files.sh
  .circleci/config.yml
  .circleci/create-hash.sh
  .circleci/defaults.sh
  .circleci/do-rtl-build.sh
  .circleci/run-tests.sh
Labels: ci, enhancement

#148 Add verbose to debug runs
  common.mk
  sims/verisim/Makefile
  sims/vsim/Makefile
  variables.mk
Labels: enhancement

#154 Address misc. issues
  .circleci/build-verilator.sh
  .circleci/check-commit.sh
  .circleci/config.yml
  .circleci/defaults.sh
  common.mk
  sims/vcs/.gitignore
  sims/vcs/Makefile
  sims/verilator/.gitignore
  sims/verilator/Makefile
  sims/verilator/verilator.mk
Labels: cleanup

#158 Update README.md with proper CI/readthedocs links
  README.md
Labels: bug

#159 Make verilator wget safe
  sims/verilator/verilator.mk
Labels: cleanup

#162 Update vlsi/Makefile to match variables.mk naming
  vlsi/Makefile
Labels: bug

#163 Hwacha CI Update
  .circleci/defaults.sh
  generators/example/src/main/scala/Configs.scala
Labels: bug, ci

#167 Unset the init for `hammer-cad-plugins`
  scripts/init-submodules-no-riscv-tools.sh
Labels: bug

#175 Fix run-binary-debug verbosity
  common.mk
Labels: bug

#177 Do not clobber LD_LIBRARY_PATH in env.sh
  scripts/build-toolchains.sh
Labels: enhancement
