Repository ucb-bar/chipyard, pull requests merged in 2019-10, with the labels that each got.

#264 Add warning directive for Mac/Windows warnings
  docs/Quick-Start.rst
Labels: docs

#268 Docs Cleanup
  README.md
  docs/Advanced-Concepts/Chip-Communication.rst
  docs/Advanced-Concepts/Top-Testharness.rst
  docs/Chipyard-Basics/Chipyard-Components.rst
  docs/Chipyard-Basics/Chipyard-Generator-Mixins.rst
  docs/Chipyard-Basics/Configs-Parameters-Mixins.rst
  docs/Chipyard-Basics/Initial-Repo-Setup.rst
  docs/Chipyard-Basics/index.rst
  docs/Generators/Rocket-Chip.rst
  docs/Generators/SHA3.rst
  docs/Generators/index.rst
  docs/Quick-Start.rst
  docs/Simulation/FPGA-Accelerated-Simulation.rst
  docs/Simulation/Running-A-Simulation.rst
  docs/Simulation/Software-RTL-Simulation.rst
  docs/Simulation/index.rst
  docs/Software/FireMarshal.rst
  docs/Tools/Barstools.rst
  docs/Tools/Chisel-Testers.rst
  docs/VLSI/Building-A-Chip.rst
  docs/VLSI/Hammer.rst
  docs/_static/images/chipyard-logo.png
  docs/_static/images/chipyard-logo.svg
  docs/conf.py
  docs/index.rst
  scripts/build-toolchains.sh
Labels: docs

#283 Update Scala TestSuite with no FireBoom
  generators/firechip/src/test/scala/ScalaTestSuite.scala
Labels: bug

#302 (master) Fix commit on master CI check
  .circleci/check-commit.sh
Labels: bug, ci

#305 Get `master` CI fix
  .circleci/check-commit.sh
Labels: bug

#304 Add a specific toolchain `env.sh`
  scripts/build-toolchains.sh
Labels: cleanup

#308 Log tests
  common.mk
  sims/vcs/Makefile
  sims/verilator/Makefile
Labels: enhancement

#307 Fix `master` CI
  .circleci/check-commit.sh
  scripts/init-submodules-no-riscv-tools.sh
Labels: bug, ci

#315 add large boom hwacha config
  generators/example/src/main/scala/BoomConfigs.scala
Labels: enhancement

#318 Fix VLSI Makefile
  vlsi/Makefile
Labels: bug
