Repository ucb-bar/chipyard, pull requests merged in 2019-05, with the labels that each got.

#78 Minor Makefile fixes
  sims/verisim/Makefile
  sims/vsim/Makefile
  variables.mk
Labels: bug, enhancement, rebar

#82 CI for Rebar
  .circleci/README.md
  .circleci/build-toolchains.sh
  .circleci/build-verilator.sh
  .circleci/config.yml
  .circleci/create-hash.sh
  .circleci/do-rtl-build.sh
  README.md
  generators/example/src/main/scala/ConfigMixins.scala
  generators/example/src/main/scala/Configs.scala
  scripts/build-toolchains.sh
  variables.mk
Labels: ci, enhancement, rebar

#88 reduce amount of sbt calls for sim
  common.mk
Labels: enhancement, rebar

#91 rename output | helper rules to run binaries
  README.md
  common.mk
  sims/verisim/Makefile
  sims/vsim/Makefile
  variables.mk
Labels: enhancement, rebar

#96 Update docs
  docs/Generators/BOOM.rst
  docs/Generators/Hwacha.rst
  docs/Generators/Rocket.rst
  docs/Generators/index.rst
  docs/Getting-Started/Adding-An-Accelerator-Tutorial.rst
  docs/Getting-Started/Configs-Parameters-Mixins.rst
  docs/Getting-Started/Development-Ecosystem.rst
  docs/Getting-Started/REBAR-Basics.rst
  docs/Getting-Started/ReBAR-Basics.rst
  docs/Getting-Started/Running-A-Simulation.rst
  docs/Getting-Started/index.rst
  docs/Getting-Started/rebar-generator-mixins.rst
  docs/Makefile
  docs/Simulation/Commercial-Simulators.rst
  docs/Simulation/FPGA-Based-Simulators.rst
  docs/Simulation/Open-Source-Simulators.rst
  docs/Simulation/index.rst
  docs/Tools/Barstools.rst
  docs/Tools/Chisel.rst
  docs/Tools/FIRRTL.rst
  docs/Tools/index.rst
  docs/VLSI/HAMMER.rst
  docs/VLSI/index.rst
  docs/conf.py
  docs/index.rst
Labels: enhancement, rebar

#93 Run Binary Default Flag Change
  variables.mk
Labels: enhancement, rebar

#98 Update README (mainly just have links to the documentation)
  README.md
Labels: enhancement, rebar
