Repository ucb-bar/chipyard, pull requests merged in 2019-11, with the labels that each got.

#327 Issue + PR Templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cleanup

#340 Fix syntax error in vlsi/Makefile
  vlsi/Makefile
Labels: bug

#345 [ci] Whitelist submodule dev branches for commit-on-dev checks
  .circleci/check-commit.sh
  .circleci/config.yml
Labels: ci
