Repository ucb-bar/chipyard, pull requests merged in 2020-05, with the labels that each got.

#557 small cleanup to issues
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/question.md
Labels: enhancement

#560 Remove Dromajo build from build-toolchains.sh
  .circleci/config.yml
  scripts/build-toolchains.sh
  scripts/init-submodules-no-riscv-tools-nolog.sh
Labels: bug

#569 Scratchpad Documentation Fix
  docs/Customization/Memory-Hierarchy.rst
  generators/chipyard/src/main/scala/config/RocketConfigs.scala
Labels: bug, docs

#577 Small CI Improvements
  .circleci/build-toolchains.sh
  .circleci/clean-old-files.sh
  .circleci/defaults.sh
  .circleci/do-rtl-build.sh
  .circleci/install-verilator.sh
  .circleci/run-firesim-scala-tests.sh
  .circleci/run-midasexamples-tests.sh
  .circleci/run-tests.sh
Labels: ci, release

#581 Add dramsim_lib as a dependency of hammer sims
  vlsi/Makefile
Labels: release

#585 Add changelog for 1.3.0 release
  CHANGELOG.md
Labels: release
