Repository ucb-bar/chipyard, pull requests merged in 2020-01, with the labels that each got.

#379 Update LICENSE
  LICENSE
Labels: cleanup

#386 Patch parallel make
  common.mk
Labels: bug

#383 Scratchpad Config
  generators/example/src/main/scala/ConfigMixins.scala
  generators/example/src/main/scala/RocketConfigs.scala
  generators/example/src/main/scala/Top.scala
  generators/example/src/main/scala/TopCakes.scala
Labels: enhancement

#393 Update documentation for release
  docs/Advanced-Concepts/Chip-Communication.rst
  docs/Advanced-Concepts/Debugging-RTL.rst
  docs/Advanced-Concepts/Top-Testharness.rst
  docs/Customization/Boot-Process.rst
  docs/Customization/Heterogeneous-SoCs.rst
  docs/Customization/Incorporating-Verilog-Blocks.rst
  docs/Customization/Keys-Traits-Configs.rst
  docs/Customization/MMIO-Peripherals.rst
  docs/Customization/Memory-Hierarchy.rst
  docs/Customization/index.rst
  docs/VLSI/Advanced-Usage.rst
  docs/_static/images/chip-bringup.png
Labels: docs

#362 [tracegen] Add tracegen support for the BOOM L1D
  .circleci/config.yml
  .circleci/defaults.sh
  .circleci/run-tests.sh
  build.sbt
  generators/tracegen/src/main/scala/Configs.scala
  generators/tracegen/src/main/scala/System.scala
  generators/tracegen/src/main/scala/Tile.scala
Labels: enhancement

#392 Enforce that macrocompiler passes are done serially
  common.mk
Labels: bug

#388 Clone firesim non-recursively
  scripts/init-submodules-no-riscv-tools.sh
Labels: DO NOT MERGE, cleanup

#413 Fix multi-rocc boom+rocket+hwacha config
  generators/example/src/main/scala/HeteroConfigs.scala
Labels: bug
