Repository ucb-bar/chipyard, pull requests merged in 2020-04, with the labels that each got.

#510 CI Run Button
  .circleci/config.yml
Labels: ci

#513 Fix bug in verilator Makefile for 'debug' rule
  sims/verilator/Makefile
Labels: bug

#519 Bypass approval button on dev/master
  .circleci/config.yml
Labels: ci

#521 Remove approval button for ci jobs
  .circleci/config.yml
Labels: ci

#518 Include scripts for dependencies in documentation
  docs/index.rst
Labels: docs

#534 Generate Rocket Chip based artefacts in FireSim
  generators/firechip/src/main/scala/Generator.scala
Labels: bug

#537 Fix "WithHeterCoresSetup" in hetero. docs
  docs/Customization/Heterogeneous-SoCs.rst
Labels: docs
