Repository ucb-bar/chipyard, pull requests merged in 2020-08, with the labels that each got.

#649 Change DIR evaluation strategy
  .circleci/config.yml
  scripts/build-toolchains.sh
  scripts/build-util.sh
  scripts/init-submodules-no-riscv-tools-nolog.sh
Labels: enhancement

#654 Multithreaded Verilator
  common.mk
  docs/Simulation/Software-RTL-Simulation.rst
  generators/utilities/src/main/resources/csrc/emulator.cc
  scripts/numa_prefix
  sims/verilator/Makefile
Labels: enhancement

#657 Dedup simulation flags + Small VCS Cleanup
  docs/Simulation/Software-RTL-Simulation.rst
  sims/common-sim-flags.mk
  sims/vcs/Makefile
  sims/verilator/Makefile
  vcs.mk
Labels: DO NOT MERGE, cleanup, enhancement

#663 Add firemarshal's dev branch to its allowed-branch list
  .circleci/check-commit.sh
Labels: ci
