Repository ucb-bar/chipyard, pull requests merged in 2021-11, with the labels that each got.

#1021 Add define for MAKE variable
  scripts/build-toolchains.sh
Labels: enhancement

#1029 Modify GH Issues (All Feedback Welcome)
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/question.md
Labels: cleanup

#1032 Update pull request template (Feedback welcome)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cleanup

#1033 Ack. NSF award
  README.md
  docs/index.rst
Labels: docs

#1035 Update README
  .github/CI_README.md
  README.md
Labels: docs

#1041 Cleanup how to override SBT + `make help` documentation update
  common.mk
  variables.mk
Labels: enhancement
