Repository ucb-bar/chipyard, pull requests merged in 2022-06, with the labels that each got.

#1170 Stage: avoid naming targets listed in RocketChiselStage
  generators/chipyard/src/main/scala/stage/ChipyardStage.scala
Labels: changelog:fixed

#1179 Comment out firesim-run-test CI due to elfutils failure
  .github/workflows/chipyard-run-tests.yml
Labels: bug

#1182 Update CHANGELOG for 1.7.0
  CHANGELOG.md
Labels: changelog:omit
