Repository ucb-bar/chipyard, pull requests merged in 2022-09, with the labels that each got.

#1218 Ignore dotfiles in lookup_srcs makefile function
  common.mk
Labels: changelog:fixed

#1223 Misc. updates to bash scripts
  .github/actions/run-tests/action.yml
  .github/scripts/remote-do-rtl-build.sh
  .github/scripts/remote-run-firesim-scala-tests.sh
  build-setup.sh
  scripts/build-toolchain-extra.sh
  scripts/firesim-setup.sh
  scripts/init-fpga.sh
  scripts/init-software.sh
  scripts/init-submodules-no-riscv-tools-nolog.sh
  scripts/init-vlsi.sh
  scripts/repo-clean.sh
  scripts/tutorial-setup.sh
  scripts/utils.sh
Labels: changelog:changed

#1228 Install espresso in build-toolchain-extra.sh
  scripts/build-toolchain-extra.sh
Labels: changelog:added

#1229 [ci skip] Fix comment for FFTRocketGenerator
  generators/chipyard/src/main/scala/config/RocketConfigs.scala
Labels: changelog:omit

#1235 [ci skip] Update CHANGELOG.md for 1.8.0
  CHANGELOG.md
Labels: changelog:omit
