Repository ucb-bar/chipyard, pull requests merged in 2022-10, with the labels that each got.

#1237 [ci skip] Fix CHANGELOG.md for 1.8.0
  CHANGELOG.md
Labels: changelog:omit

#1238 [ci skip] Give all scripts +x permissions
  scripts/build-util.sh
  scripts/repo-clean.sh
  scripts/utils.sh
Labels: changelog:omit

#1241 Update stable docs
  docs/conf.py
Labels: bug, Please Backport, changelog:omit

#1246 Fix fd command
  common.mk
Labels: changelog:omit

#1249 Misc release cleanup
  .gitattributes
  .github/actions/create-conda-env/action.yml
  .gitignore
  build-setup.sh
  common.mk
  conda-reqs/chipyard.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
  conda-reqs/esp-tools.yaml
  conda-reqs/riscv-tools.yaml
  conda-requirements-riscv-tools.yaml
  scripts/init-submodules-no-riscv-tools-nolog.sh
Labels: cleanup

#1251 Revert to using sbt-launch.jar to run SBT
  variables.mk
Labels: changelog:fixed

#1252 Default VCS simulators should generate FSDB
  docs/VLSI/ASAP7-Tutorial.rst
  docs/VLSI/Sky130-Commercial-Tutorial.rst
  vcs.mk
  vlsi/Makefile
Labels: changelog:changed
