Repository ucb-bar/chipyard, pull requests merged in 2022-02, with the labels that each got.

#1102 FSDB support in VLSI flow
  vlsi/Makefile
Labels: enhancement

#1104 Update BOOM reference in README
  README.md
Labels: bug, docs

#1105 Remove CircleCI
  .circleci/README.md
  .circleci/build-extra-tests.sh
  .circleci/build-toolchains.sh
  .circleci/check-commit.sh
  .circleci/clean-old-files.sh
  .circleci/config.yml
  .circleci/create-hash.sh
  .circleci/defaults.sh
  .circleci/do-rtl-build.sh
  .circleci/install-verilator.sh
  .circleci/run-firesim-scala-tests.sh
  .circleci/run-tests.sh
Labels: ci, cleanup

#1108 Fix SAIF & Waveforms for Post-P&R Power
  vlsi/Makefile
  vlsi/power.mk
Labels: bug
