Repository ucb-bar/chipyard, pull requests merged in 2023-11, with the labels that each got.

#1643 [ci] Update check-commit with missing submodules
  .github/scripts/check-commit.sh
Labels: changelog:omit

#1644 [ci skip] Fix funding ack
  README.md
Labels: changelog:omit

#1640 Fix regex for similar module names that are uniquified
  scripts/uniquify-module-names.py
Labels: changelog:fixed

#1639 Rebuild `jar`s when `sv`/`v` files are changed + Add documentation on blackboxes
  common.mk
  conda-reqs/chipyard.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
  docs/Customization/Incorporating-Verilog-Blocks.rst
  generators/chipyard/src/main/scala/example/GCD.scala
  scripts/generate-conda-lockfiles.sh
  scripts/insert-includes.py
  tests/gcd.c
Labels: bug, changelog:fixed

#1649 Run only on old-ci machines
  .github/workflows/chipyard-run-tests.yml
Labels: changelog:omit

#1650 Update to use the new CI machines
  .github/workflows/chipyard-full-flow.yml
  .github/workflows/chipyard-run-tests.yml
Labels: changelog:omit

#1647 Use TARGET instead of PREFIX in /tests Makefile(s)
  tests/Makefile
  tests/libgloss.mk
Labels: bug, changelog:fixed

#1654 Fix IO direction for host Serial-TL port
  generators/chipyard/src/main/scala/iobinders/IOBinders.scala
Labels: changelog:fixed

#1653 More robust env.sh | Fix conda activate if in subshell
  scripts/build-setup.sh
  scripts/init-submodules-no-riscv-tools-nolog.sh
  scripts/replace-content.py
  scripts/utils.sh
Labels: changelog:fixed

#1660 Move memory system configs to a separate configs file
  docs/Customization/Memory-Hierarchy.rst
  generators/chipyard/src/main/scala/config/MemorySystemConfigs.scala
  generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
  generators/chipyard/src/main/scala/config/RocketConfigs.scala
Labels: changelog:omit

#1662 Hammer bump and minor VLSI fixes
  .github/workflows/chipyard-full-flow.yml
  conda-reqs/chipyard.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
  docs/VLSI/Sky130-Commercial-Tutorial.rst
  docs/VLSI/Sky130-OpenROAD-Tutorial.rst
  vlsi/Makefile
  vlsi/sim.mk
Labels: changelog:omit

#1664 Add RocketBoundaryBuffers fragment
  generators/chipyard/src/main/scala/config/fragments/TileFragments.scala
Labels: changelog:omit

#1665 Update TargetConfigs.scala for 64G comment.
  generators/firechip/src/main/scala/TargetConfigs.scala
Labels: changelog:omit

#1667 Add cfg fragment to insert LLC interior/exterior buffers
  generators/chipyard/src/main/scala/config/fragments/SubsystemFragments.scala
Labels: changelog:omit

#1657 Add Bringup on Arty100T config, using PMOD-gpio for ser-tl
  fpga/src/main/scala/arty100t/Configs.scala
  fpga/src/main/scala/arty100t/HarnessBinders.scala
  generators/chipyard/src/main/scala/config/fragments/ClockingFragments.scala
Labels: changelog:added

#1668 Always generate MFC Blackbox filelist
  common.mk
Labels: changelog:fixed

#1672 Allow overriding generated-src dir name
  variables.mk
Labels: changelog:omit
