Repository ucb-bar/chipyard, pull requests merged in 2023-07, with the labels that each got.

#1540 Docs add that ASAP7 tutorial should be executed in vlsi directory
  docs/VLSI/ASAP7-Tutorial.rst
Labels: docs, changelog:omit

#1535 ADD: add documentation for build-setup skip
  docs/Chipyard-Basics/Initial-Repo-Setup.rst
Labels: docs, changelog:added

#1547 Add weekly CI cron job
  .github/workflows/chipyard-full-flow.yml
Labels: changelog:added

#1544 Bump Conda + Deprecate docker image docs
  .github/scripts/install-conda.sh
  docs/Chipyard-Basics/Initial-Repo-Setup.rst
Labels: changelog:changed

#1548 Add release note automation
  .github/workflows/config/release-notes.json
  .github/workflows/release-notes.yml
  .github/workflows/require-label.yml
  .mergify.yml
Labels: changelog:added

#1527 Improve peripheral config binders (Reapply #1511)
  .gitignore
  generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
  generators/firechip/src/main/scala/TargetConfigs.scala
  tests/spiflash.h
Labels: changelog:added

#1554 Use new CI machines
  .github/scripts/remote-run-firesim-scala-tests.sh
  .github/workflows/chipyard-full-flow.yml
  .github/workflows/chipyard-run-tests.yml
Labels: changelog:omit

#1555 Bump lockfiles | Force user-installed conda during conda-lock
  .github/actions/create-conda-env/action.yml
  .github/scripts/install-conda.sh
  conda-reqs/chipyard.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
  docs/Chipyard-Basics/Initial-Repo-Setup.rst
  scripts/build-setup.sh
  scripts/generate-conda-lockfiles.sh
Labels: changelog:fixed

#1347 UPF Generation
  build.sbt
  common.mk
  docs/VLSI/Advanced-Usage.rst
  generators/chipyard/src/main/scala/harness/TestHarness.scala
  generators/chipyard/src/main/scala/upf/ChipTopUPF.scala
  generators/chipyard/src/main/scala/upf/UPFAspect.scala
  generators/chipyard/src/main/scala/upf/UPFGen.scala
  generators/chipyard/src/main/scala/upf/UPFInputs.scala
Labels: changelog:added

#1563 Fix FIFO-fixing for PRCI bus
  generators/chipyard/src/main/scala/clocking/ClockBinders.scala
  generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala
Labels: changelog:fixed
