Repository ucb-bar/chipyard, pull requests merged in 2023-05, with the labels that each got.

#1454 Use pk/encoding.h for hello/mt-hello
  tests/encoding.h
  tests/hello.c
  tests/mt-hello.c
Labels: changelog:omit

#1457 Fix no-uart configs
  generators/chipyard/src/main/scala/Subsystem.scala
Labels: changelog:fixed

#1458 Fix support for no-bootROM systems
  generators/chipyard/src/main/scala/System.scala
Labels: changelog:fixed

#1459 Support not instantiating the TileClockGater/ResetSetter PRCI control
  generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala
  generators/chipyard/src/main/scala/clocking/TileClockGater.scala
Labels: changelog:changed

#1460 Check that HarnessClockInstantiator doesn't receive requests for similarly-named-clocks with different frequencies
  generators/chipyard/src/main/scala/HarnessClocks.scala
Labels: changelog:added

#1456 Always initialize fpga-shells with init-submodules.sh
  .github/scripts/remote-do-rtl-build.sh
  docs/Prototyping/General.rst
  scripts/build-setup.sh
  scripts/init-fpga.sh
  scripts/init-submodules-no-riscv-tools-nolog.sh
Labels: changelog:changed

#1463 Move TestHarness to chipyard.harness, make chipyard/harness directory
  docs/Advanced-Concepts/Harness-Clocks.rst
  docs/Customization/IOBinders.rst
  docs/VLSI/ASAP7-Tutorial.rst
  docs/VLSI/Sky130-Commercial-Tutorial.rst
  docs/VLSI/Sky130-OpenROAD-Tutorial.rst
  fpga/src/main/scala/arty/TestHarness.scala
  fpga/src/main/scala/arty100t/Harness.scala
  fpga/src/main/scala/vc707/Configs.scala
  fpga/src/main/scala/vc707/TestHarness.scala
  fpga/src/main/scala/vcu118/Configs.scala
  fpga/src/main/scala/vcu118/HarnessBinders.scala
  fpga/src/main/scala/vcu118/TestHarness.scala
  fpga/src/main/scala/vcu118/bringup/HarnessBinders.scala
  generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala
  generators/chipyard/src/main/scala/config/ChipConfigs.scala
  generators/chipyard/src/main/scala/config/fragments/ClockingFragments.scala
  generators/chipyard/src/main/scala/example/CustomChipTop.scala
  generators/chipyard/src/main/scala/example/FlatTestHarness.scala
  generators/chipyard/src/main/scala/harness/HarnessBinders.scala
  generators/chipyard/src/main/scala/harness/HarnessClocks.scala
  generators/chipyard/src/main/scala/harness/TestHarness.scala
  generators/firechip/src/main/scala/BridgeBinders.scala
  variables.mk
Labels: changelog:omit

#1471 Add 1GB / 4GB DRAM firechip configs for FireSim VCU118
  generators/firechip/src/main/scala/TargetConfigs.scala
Labels: changelog:omit

#1473 Fix vcd/fst/fsdb waveform generation
  sims/vcs/vcs.mk
  sims/verilator/Makefile
Labels: changelog:omit

#1472 Switch RTL sims to absolute clock-generators
  .github/scripts/defaults.sh
  fpga/src/main/scala/arty/Configs.scala
  fpga/src/main/scala/arty/TestHarness.scala
  fpga/src/main/scala/arty100t/Configs.scala
  fpga/src/main/scala/arty100t/Harness.scala
  fpga/src/main/scala/vc707/Configs.scala
  fpga/src/main/scala/vc707/TestHarness.scala
  fpga/src/main/scala/vcu118/Configs.scala
  fpga/src/main/scala/vcu118/TestHarness.scala
  generators/chipyard/src/main/scala/IOBinders.scala
  generators/chipyard/src/main/scala/clocking/ClockBinders.scala
  generators/chipyard/src/main/scala/clocking/DividerOnlyClockGenerator.scala
  generators/chipyard/src/main/scala/config/AbstractConfig.scala
  generators/chipyard/src/main/scala/config/RocketConfigs.scala
  generators/chipyard/src/main/scala/config/TracegenConfigs.scala
  generators/chipyard/src/main/scala/harness/HarnessBinders.scala
  generators/chipyard/src/main/scala/harness/HarnessClocks.scala
  generators/chipyard/src/main/scala/harness/TestHarness.scala
Labels: changelog:changed

#1467 Generate objdump | check BINARY | cospike fixes
  common.mk
  generators/chipyard/src/main/resources/csrc/cospike.cc
Labels: changelog:changed
