Repository ucb-bar/chipyard, pull requests merged in 2023-08, with the labels that each got.

#1578 Improve: SiFive peripheral device doumentation
  docs/Generators/SiFive-Generators.rst
Labels: changelog:added

#1580 Support variable VLEN cosim
  generators/chipyard/src/main/resources/csrc/cospike.cc
  generators/chipyard/src/main/resources/vsrc/cospike.v
  generators/chipyard/src/main/scala/Cospike.scala
  generators/chipyard/src/main/scala/harness/HarnessBinders.scala
Labels: changelog:omit

#1585 Enable precommit | Format files
  docs/Advanced-Concepts/Architectural-Checkpoints.rst
  docs/Advanced-Concepts/Harness-Clocks.rst
  docs/Customization/Custom-Chisel.rst
  docs/Customization/RoCC-Accelerators.rst
  docs/Generators/SiFive-Generators.rst
  docs/Simulation/Software-RTL-Simulation.rst
  docs/VLSI/Advanced-Usage.rst
  docs/VLSI/Sky130-Commercial-Tutorial.rst
  docs/VLSI/Sky130-OpenROAD-Tutorial.rst
  generators/chipyard/src/main/resources/csrc/cospike.cc
  generators/chipyard/src/main/resources/vsrc/spiketile.v
  generators/chipyard/src/main/scala/clocking/DividerOnlyClockGenerator.scala
  generators/chipyard/src/main/scala/clocking/TileClockGater.scala
  generators/chipyard/src/main/scala/config/BoomConfigs.scala
  generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
  generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
  generators/chipyard/src/main/scala/stage/ChipyardOptions.scala
  scripts/build-setup.sh
  scripts/generate-ckpt.sh
  scripts/tutorial-patches/build.sbt.patch
  scripts/uniquify-module-names.py
  sims/xcelium/.gitignore
  sims/xcelium/arg-reshuffle
  sims/xcelium/xcelium.mk
  software/embench/build.sh
  vlsi/example-designs/sky130-commercial.yml
  vlsi/example-designs/sky130-openroad-rockettile.yml
  vlsi/example-designs/sky130-openroad.yml
Labels: changelog:added

#1587 Remove pre-commit from env.sh
  scripts/build-setup.sh
Labels: changelog:removed
