Repository ucb-bar/chipyard, pull requests merged in 2023-09, with the labels that each got.

#1584 Clarify fragments in ChipLikeRocketConfigs.scala
  generators/chipyard/src/main/scala/config/ChipConfigs.scala
Labels: changelog:omit

#1514 KLayout section of Sky130+OpenROAD tutorial
  .github/workflows/chipyard-full-flow.yml
  conda-reqs/chipyard.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
  docs/VLSI/Sky130-OpenROAD-Tutorial.rst
  docs/_static/images/vlsi-openroad-klayout-drc.png
  vlsi/example-openroad.yml
Labels: changelog:added

#1597 Fix VCU118 freq adjustment configs
  fpga/src/main/scala/vcu118/Configs.scala
Labels: changelog:fixed

#1602 Updated docs on waveform generation to match current workflow.
  docs/Simulation/Software-RTL-Simulation.rst
Labels: changelog:omit
