Repository ucb-bar/chipyard, pull requests merged in 2023-12, with the labels that each got.

#1680 fix blkdev test
  tests/blkdev.c
Labels: changelog:omit

#1682 REFACTOR: rename arty35t explicitly
  .github/scripts/defaults.sh
  fpga/Makefile
  fpga/src/main/scala/arty/HarnessBinders.scala
  fpga/src/main/scala/arty/TestHarness.scala
Labels: changelog:changed

#1674 Add HasHarnessInstantiators into MultiHarnessBinder
  generators/chipyard/src/main/scala/harness/MultiHarnessBinders.scala
  generators/chipyard/src/main/scala/harness/package.scala
Labels: changelog:changed

#1695 Remove references to ENABLE_YOSYS
  common.mk
  docs/VLSI/Sky130-Commercial-Tutorial.rst
  docs/VLSI/Sky130-OpenROAD-Tutorial.rst
  vlsi/example-designs/sky130-openroad-rockettile.yml
  vlsi/example-designs/sky130-openroad.yml
  vlsi/example-sky130.yml
  vlsi/tutorial.mk
Labels: changelog:fixed

#1698 replace-content.py should use python3 explicitly
  scripts/replace-content.py
Labels: changelog:omit

#1685 FIX: fix vcu118 sd card frequency
  fpga/src/main/resources/vcu118/sdboot/sd.c
Labels: changelog:fixed

#1712 Add UART device/JTAG to Arty100T default design
  fpga/src/main/scala/arty100t/Configs.scala
  fpga/src/main/scala/arty100t/Harness.scala
  fpga/src/main/scala/arty100t/HarnessBinders.scala
Labels: changelog:added
