Repository ucb-bar/chipyard, pull requests merged in 2023-02, with the labels that each got.

#1307 Spike-as-a-Tile
  .github/actions/create-conda-env/action.yml
  .github/scripts/defaults.sh
  .github/scripts/run-tests.sh
  .github/workflows/chipyard-run-tests.yml
  docs/Software/Spike.rst
  generators/chipyard/src/main/resources/csrc/spiketile.cc
  generators/chipyard/src/main/resources/vsrc/spiketile.v
  generators/chipyard/src/main/scala/SpikeTile.scala
  generators/chipyard/src/main/scala/config/SpikeConfigs.scala
  generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
  sims/common-sim-flags.mk
Labels: changelog:added

#1321 Fix compile breaking due to merge conflict
  generators/chipyard/src/main/scala/SpikeTile.scala
Labels: changelog:omit

#1336 Makefile bug fixes
  common.mk
Labels: enhancement

#1340 Split up RocketConfigs.scala
  docs/Advanced-Concepts/Chip-Communication.rst
  docs/Customization/DMA-Devices.rst
  docs/Customization/Dsptools-Blocks.rst
  docs/Customization/Incorporating-Verilog-Blocks.rst
  docs/Customization/Keys-Traits-Configs.rst
  docs/Customization/MMIO-Peripherals.rst
  docs/Customization/Memory-Hierarchy.rst
  docs/Customization/NoC-SoCs.rst
  docs/Generators/SiFive-Generators.rst
  docs/Generators/fft.rst
  generators/chipyard/src/main/scala/config/BoomConfigs.scala
  generators/chipyard/src/main/scala/config/MMIOAcceleratorConfigs.scala
  generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
  generators/chipyard/src/main/scala/config/RoCCAcceleratorConfigs.scala
  generators/chipyard/src/main/scala/config/RocketConfigs.scala
  generators/firechip/src/main/scala/TargetConfigs.scala
Labels: changelog:changed

#1337 Set VLOG_MODEL=MODEL by default in variables.mk
  variables.mk
Labels: changelog:changed

#1348 Fix VLSI input files list emission to avoid bash "too many arguments" error
  vlsi/Makefile
  vlsi/power.mk
  vlsi/sim.mk
Labels: changelog:omit

#1353 Fix socket name length issues on CI
  .github/scripts/defaults.sh
  .github/scripts/remote-do-rtl-build.sh
  .github/scripts/remote-run-firesim-scala-tests.sh
  .github/workflows/chipyard-full-flow.yml
  variables.mk
Labels: changelog:omit

#1354 Fix TestDriver.v missing from gen-collateral after recompiling
  fpga/Makefile
  sims/vcs/Makefile
  sims/verilator/Makefile
  vlsi/Makefile
Labels: bug

#1360 Override spike's misa in cosim mode
  generators/chipyard/src/main/resources/csrc/cospike.cc
Labels: changelog:changed

#1359 Reduce test cases for noc-config in CI
  .github/scripts/run-tests.sh
Labels: changelog:omit

#1365 Fix newline in message in build-setup.sh
  scripts/build-setup.sh
Labels: changelog:omit

#1368 Fix & clarify hierarchical flows
  docs/VLSI/Advanced-Usage.rst
  docs/VLSI/Basic-Flow.rst
  vlsi/power.mk
Labels: bug, changelog:fixed
