Repository ucb-bar/chipyard, pull requests merged in 2023-04, with the labels that each got.

#1425 Ensure conda cleanup regex properly filters out non-numeric chars
  .github/actions/cleanup-conda/action.yml
Labels: changelog:omit

#1424 New Scala-based Config Finder
  build.sbt
  common.mk
  docs/Customization/Keys-Traits-Configs.rst
  generators/chipyard/src/main/scala/ConfigFinder.scala
  scripts/config-finder.py
Labels: enhancement

#1430 Resolve merge conflicts in chisel3.5.6 bump
  generators/chipyard/src/main/scala/ConfigFinder.scala
  generators/chipyard/src/main/scala/example/CustomChipTop.scala
Labels: changelog:omit

#1427 PLL integration example + FlatChipTop/TestHarness
  .github/scripts/defaults.sh
  generators/chipyard/src/main/scala/HarnessBinders.scala
  generators/chipyard/src/main/scala/HarnessClocks.scala
  generators/chipyard/src/main/scala/IOBinders.scala
  generators/chipyard/src/main/scala/TestHarness.scala
  generators/chipyard/src/main/scala/clocking/ClockBinders.scala
  generators/chipyard/src/main/scala/clocking/FakePLL.scala
  generators/chipyard/src/main/scala/clocking/TLClockDivider.scala
  generators/chipyard/src/main/scala/clocking/TLClockSelector.scala
  generators/chipyard/src/main/scala/clocking/TileClockGater.scala
  generators/chipyard/src/main/scala/clocking/TileResetSetter.scala
  generators/chipyard/src/main/scala/config/AbstractConfig.scala
  generators/chipyard/src/main/scala/config/ChipConfigs.scala
  generators/chipyard/src/main/scala/config/RocketConfigs.scala
  generators/chipyard/src/main/scala/config/TracegenConfigs.scala
  generators/chipyard/src/main/scala/example/FlatChipTop.scala
  generators/chipyard/src/main/scala/example/FlatTestHarness.scala
Labels: changelog:added

#1439 ADD: improve Makefile in tests/, add explicit arch flags
  tests/Makefile
Labels: changelog:omit

#1451 Bump to Hammer 1.1.1
  conda-reqs/chipyard.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
Labels: changelog:changed

#1442 Uniquify module names that are common to Top & Model
  common.mk
  scripts/uniqify-module-names.py
  variables.mk
  vlsi/sim.mk
Labels: changelog:fixed
