Repository ucb-bar/chipyard, pull requests merged in 2024-07, with the labels that each got.

#1921 Add makefile flag to disable binary disassembly during sims
  common.mk
  variables.mk
Labels: changelog:added

#1920 Improve build-circt-from-source script for conda-less users
  scripts/build-circt-from-source.sh
Labels: changelog:omit

#1927 Bump to chisel 6.5.0
  build.sbt
  tools/stage/src/main/scala/ChipyardStage.scala
Labels: changelog:changed

#1931 Update docs
  .github/workflows/weekly-tag.yml
  README.md
  docs/Chipyard-Basics/Initial-Repo-Setup.rst
  docs/conf.py
Labels: changelog:omit

#1933 Remove non-existent tb_seq_mems prerequisite
  common.mk
  variables.mk
Labels: changelog:omit
