Repository ucb-bar/chipyard, pull requests merged in 2024-03, with the labels that each got.

#1808 Fix build-circt-from-source
  scripts/build-circt-from-source.sh
Labels: changelog:omit

#1815 REFACTOR: minor fix on code styling
  .gitmodules
Labels: changelog:changed

#1683 FIX: Change default UART FIFO size and combine UART Config fragments
  generators/chipyard/src/main/scala/config/SpikeConfigs.scala
  generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
  generators/firechip/src/main/scala/TargetConfigs.scala
Labels: changelog:fixed

#1813 REFACTOR: rearrange gitsubmodule list to match directory order
  .gitmodules
Labels: changelog:changed

#1823 Add GPIOPunchthrough harnessbinder
  generators/chipyard/src/main/scala/config/AbstractConfig.scala
  generators/chipyard/src/main/scala/harness/HarnessBinders.scala
Labels: changelog:added

#1826 Fix InitZero example + add to CI
  generators/chipyard/src/main/scala/config/MMIOAcceleratorConfigs.scala
  generators/chipyard/src/main/scala/example/InitZero.scala
Labels: changelog:fixed
