Repository ucb-bar/chipyard, pull requests merged in 2024-09, with the labels that each got.

#2032 Fix floorplan for example Sky130 VLSI flow
  vlsi/example-designs/sky130-openroad-rockettile.yml
  vlsi/example-designs/sky130-openroad.yml
  vlsi/example-designs/sky130-rocket.yml
  vlsi/example-sky130.yml
Labels: changelog:omit

#2034 Fix accidentally included modifications to example yaml
  vlsi/example-sky130.yml
Labels: changelog:omit

#2036 ADD: Add CMake build option for tests and example C++ program
  .github/scripts/build-extra-tests.sh
  .github/scripts/run-tests.sh
  .gitignore
  docs/Software/Baremetal.rst
  scripts/build-tests.sh
  tests/CMakeLists.txt
  tests/Makefile
  tests/cpp-hello.cpp
  tests/libgloss.mk
  tests/spiflash.py
Labels: changelog:added

#2051 ADD: add dump flow and documentation on tests building
  scripts/build-tests.sh
  tests/CMakeLists.txt
  tests/README.md
Labels: changelog:fixed

#2056 Add example accelerator using HLS
  .github/scripts/defaults.sh
  docs/Customization/Incorporating-HLS.rst
  docs/Customization/index.rst
  generators/chipyard/src/main/resources/hls/HLSAccel.cpp
  generators/chipyard/src/main/resources/hls/Makefile
  generators/chipyard/src/main/resources/hls/run_hls.tcl
  generators/chipyard/src/main/scala/config/MMIOAcceleratorConfigs.scala
  generators/chipyard/src/main/scala/example/GCD.scala
Labels: changelog:added

#2066 Add CHANGELOG for 1.13.0 release
  CHANGELOG.md
Labels: changelog:omit, ci:disable
