Repository ucb-bar/chipyard, pull requests merged in 2024-06, with the labels that each got.

#1897 Remove firesim build.sbt from our SBT dependencies
  common.mk
Labels: changelog:omit

#1898 add upper bound for python version to avoid incompatible packages
  conda-reqs/chipyard-extended.yaml
Labels: changelog:changed

#1899 Generate a log file of the CIRCT output
  common.mk
  variables.mk
Labels: changelog:added

#1909 Update checkpointing script
  scripts/generate-ckpt.sh
Labels: changelog:changed

#1908 Update ClockGroup aggregation error to be more descriptive
  generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala
Labels: changelog:omit

#1910 Non-recursive clone of compress-acc
  scripts/init-submodules-no-riscv-tools-nolog.sh
Labels: changelog:changed
