Repository ucb-bar/chipyard, pull requests merged in 2024-02, with the labels that each got.

#1786 Add large boom cospike config
  generators/firechip/src/main/scala/TargetConfigs.scala
Labels: changelog:added

#1722 CHANGE: Organize abstract config into sections and change comment format to docstrings
  generators/chipyard/src/main/scala/config/AbstractConfig.scala
Labels: changelog:changed

#1763 Enable debug SBA on all default designs
  generators/chipyard/src/main/scala/config/AbstractConfig.scala
Labels: changelog:added

#1792 Allow passing BINARY_ARGS to target binaries (pk)
  common.mk
  variables.mk
Labels: changelog:added

#1798 Fix invalid escape sequences
  scripts/uniquify-module-names.py
Labels: changelog:fixed

#1795 docs: Update FireSim docs
  docs/Chipyard-Basics/Initial-Repo-Setup.rst
  docs/Simulation/FPGA-Accelerated-Simulation.rst
Labels: changelog:fixed

#1800 Bump to Verilator v5.022
  conda-reqs/chipyard-base.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64-lean.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64-lean.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
Labels: changelog:changed
