Repository ucb-bar/chipyard, pull requests merged in 2024-08, with the labels that each got.

#1937 Release 1.12 changelog
  CHANGELOG.md
Labels: changelog:omit

#1939 Delete .github/workflows/weekly-tag.yml
  .github/workflows/weekly-tag.yml
Labels: changelog:removed

#1940 Add dependabot to auto-update submodules
  .github/dependabot.yml
Labels: changelog:added

#1941 Remove need for users to install conda-lock themselves
  .gitignore
  conda-reqs/chipyard-base.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64-lean.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
  docs/Chipyard-Basics/Initial-Repo-Setup.rst
  scripts/build-setup.sh
Labels: changelog:changed

#1950 Update dependabot to also update GH-A workflows
  .github/CI_README.md
  .github/dependabot.yml
  .github/scripts/defaults.sh
  .github/workflows/chipyard-full-flow.yml
  .github/workflows/chipyard-run-tests.yml
Labels: changelog:added

#1957 Cleaner CI conda env setup | Selective weekly dependabot updates
  .github/actions/cleanup-conda/action.yml
  .github/actions/create-conda-env/action.yml
  .github/actions/prepare-rtl/action.yml
  .github/actions/run-tests/action.yml
  .github/dependabot.yml
  .github/workflows/chipyard-run-tests.yml
  .github/workflows/update-circt.yml
  scripts/build-setup.sh
Labels: changelog:changed

#1963 Fix VLSI CI - Fix conda environment creation
  .github/workflows/chipyard-full-flow.yml
Labels: changelog:fixed

#1964 Shift CIRCT updates to weekly
  .github/workflows/update-circt.yml
Labels: changelog:omit

#1965 Run CI out of larger scratch directory
  .github/workflows/chipyard-full-flow.yml
Labels: changelog:omit

#1970 Update build-setup.sh
  scripts/build-setup.sh
Labels: changelog:fixed

#1942 Nexys video fpga bringup config
  fpga/src/main/scala/nexysvideo/Configs.scala
  fpga/src/main/scala/nexysvideo/HarnessBinders.scala
Labels: changelog:added

#1977 Update Initial-Repo-Setup.rst
  docs/Chipyard-Basics/Initial-Repo-Setup.rst
Labels: changelog:added

#1978 Update generate-conda-lockfiles.sh
  scripts/generate-conda-lockfiles.sh
Labels: changelog:fixed

#1985 Add CI disable flag
  .github/workflows/chipyard-full-flow.yml
  .github/workflows/chipyard-run-tests.yml
Labels: changelog:omit, ci:disable

#1990 Mention vector units README
  README.md
Labels: changelog:omit, ci:disable

#2012 Update CHANGELOG.md
  CHANGELOG.md
Labels: changelog:omit, ci:disable

#2023 WIP: More robust Github bitstream uploads
  .github/scripts/build-default-bitstreams.py
  .github/scripts/ci_variables.py
  .github/scripts/github_common.py
  .github/workflows/firesim-cluster-tests.yml
  common.mk
  conda-reqs/chipyard-extended.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64-lean.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
Labels: DO NOT MERGE, changelog:omit, ci:local-fpga-buildbitstream-deploy

#2022 Add CI help text to PR template | Reduce more CI runs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/chipyard-full-flow.yml
  .github/workflows/chipyard-run-tests.yml
  .github/workflows/firesim-cluster-tests.yml
Labels: changelog:added

#2025 Add WithUniformBusFrequencies | Fix UARTTSI HarnessBinder
  fpga/src/main/scala/arty/Configs.scala
  fpga/src/main/scala/arty100t/Configs.scala
  fpga/src/main/scala/nexysvideo/Configs.scala
  fpga/src/main/scala/vc707/Configs.scala
  fpga/src/main/scala/vcu118/Configs.scala
  generators/chipyard/src/main/scala/config/ChipConfigs.scala
  generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
  generators/chipyard/src/main/scala/config/SpikeConfigs.scala
  generators/chipyard/src/main/scala/config/TracegenConfigs.scala
  generators/chipyard/src/main/scala/config/fragments/ClockingFragments.scala
  generators/chipyard/src/main/scala/harness/HarnessBinders.scala
Labels: changelog:omit
