Repository ucb-bar/chipyard, pull requests merged in 2024-01, with the labels that each got.

#1704 Move CIRCT install to its own step in build-setup script
  scripts/build-setup.sh
Labels: changelog:omit

#1714 FIX: fix conda-lock version, >1.4.0 does not work!
  docs/Chipyard-Basics/Initial-Repo-Setup.rst
Labels: changelog:fixed

#1717 Remove esp-conda-env from CI conda envs
  .github/actions/create-conda-env/action.yml
Labels: changelog:omit

#1718 Add generators/ submodule status check to all Make targets
  common.mk
Labels: changelog:added

#1724 Add clearer --skip flags to build-setup
  scripts/build-setup.sh
Labels: changelog:added

#1728 Fix check-submodule-status forcing rebuilds
  common.mk
Labels: changelog:omit

#1725 Fix missing childClock/childReset in Arty100THarness
  fpga/src/main/scala/arty100t/Harness.scala
Labels: changelog:omit

#1730 ADD: add information on Baremetal-IDE in docs
  docs/Chipyard-Basics/Chipyard-Components.rst
Labels: changelog:added

#1706 Rename timeout_cycles to TIMEOUT_CYCLES to match convention
  variables.mk
  vlsi/power.mk
  vlsi/sim.mk
Labels: changelog:changed

#1697 Add debug clock tap port to all default designs
  generators/chipyard/src/main/scala/DigitalTop.scala
  generators/chipyard/src/main/scala/clocking/CanHaveClockTap.scala
  generators/chipyard/src/main/scala/clocking/ClockBinders.scala
  generators/chipyard/src/main/scala/clocking/TLClockDivider.scala
  generators/chipyard/src/main/scala/clocking/TLClockSelector.scala
  generators/chipyard/src/main/scala/config/AbstractConfig.scala
  generators/chipyard/src/main/scala/config/ChipConfigs.scala
  generators/chipyard/src/main/scala/config/RocketConfigs.scala
  generators/chipyard/src/main/scala/config/fragments/ClockingFragments.scala
  generators/chipyard/src/main/scala/iobinders/IOBinders.scala
  generators/chipyard/src/main/scala/iobinders/Ports.scala
  generators/firechip/src/main/scala/TargetConfigs.scala
Labels: changelog:added

#1745 Makefile: add print-FOO utility target that prints the value of a make variable
  common.mk
Labels: changelog:omit

#1744 docs: correct to TOP_MACROCOMPILER_MODE
  docs/VLSI/Basic-Flow.rst
Labels: changelog:fixed

#1742 Use non-lock-file conda requirements in RTD
  .readthedocs.yml
  conda-reqs/chipyard.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
  conda-reqs/docs.yaml
  scripts/generate-conda-lockfiles.sh
Labels: DO NOT MERGE, changelog:fixed

#1749 Remove skip-validate option
  .github/actions/run-tests/action.yml
  .github/scripts/remote-do-rtl-build.sh
  .github/scripts/remote-run-firesim-scala-tests.sh
  .github/workflows/chipyard-full-flow.yml
  .github/workflows/chipyard-run-tests.yml
  scripts/build-setup.sh
  scripts/init-submodules-no-riscv-tools-nolog.sh
Labels: changelog:changed

#1754 Add .gitignore for Embench Build Folder
  software/embench/.gitignore
Labels: changelog:changed

#1752 FastSimRocketConfig with no TLMonitors
  docs/Simulation/Software-RTL-Simulation.rst
  generators/chipyard/src/main/scala/config/RocketConfigs.scala
Labels: changelog:added

#1750 Use lean conda for faster initial setup
  conda-reqs/chipyard-base.yaml
  conda-reqs/chipyard-extended.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64-lean.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64-lean.conda-lock.yml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
  scripts/build-setup.sh
  scripts/generate-conda-lockfiles.sh
Labels: changelog:added

#1755 Add BroadcastCoherence rocket config
  generators/chipyard/src/main/scala/config/MemorySystemConfigs.scala
Labels: changelog:added

#1758 Fix unnecessary runs/rebuilds of RTL simulators
  common.mk
  scripts/split-mems-conf.py
Labels: changelog:fixed

#1759 Remove useless conda env sourcing
  scripts/build-setup.sh
Labels: changelog:removed

#1765 Fix submodule recusive cloning
  .gitmodules
  scripts/init-submodules-no-riscv-tools-nolog.sh
Labels: changelog:fixed

#1757 Improve GCD example
  docs/Customization/MMIO-Peripherals.rst
  generators/chipyard/src/main/scala/example/GCD.scala
Labels: changelog:changed

#1772 Update dead doc links
  docs/Customization/Boot-Process.rst
  docs/Generators/Hwacha.rst
Labels: changelog:omit

#1773 Support BINARIES_DIR make flag
  variables.mk
Labels: changelog:added

#1774 Update MMIO peripheral docs
  docs/Customization/Incorporating-Verilog-Blocks.rst
  docs/Customization/MMIO-Peripherals.rst
  docs/TileLink-Diplomacy-Reference/NodeTypes.rst
  docs/TileLink-Diplomacy-Reference/Register-Node.rst
  docs/TileLink-Diplomacy-Reference/index.rst
Labels: changelog:changed
