Repository ucb-bar/chipyard, pull requests merged in 2024-04, with the labels that each got.

#1847 Use SV48 when possible
  generators/chipyard/src/main/scala/config/AbstractConfig.scala
  generators/chipyard/src/main/scala/config/fragments/TileFragments.scala
Labels: changelog:changed

#1848 Update build-toolchain-extra.sh
  scripts/build-toolchain-extra.sh
Labels: changelog:fixed

#1856 Automatically set `DTSTimebase` to PBUS frequency
  fpga/src/main/scala/arty/Configs.scala
  generators/chipyard/src/main/scala/config/fragments/ClockingFragments.scala
  generators/chipyard/src/main/scala/config/fragments/SubsystemFragments.scala
Labels: changelog:changed

#1845 Add EmptyChipTop example
  docs/Advanced-Concepts/Top-Testharness.rst
  generators/chipyard/src/main/scala/config/NoCoreConfigs.scala
  generators/chipyard/src/main/scala/example/EmptyChipTop.scala
  generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala
  scripts/split-mems-conf.py
Labels: changelog:added

#1859 Remove legacy SFC flags
  common.mk
  docs/Customization/Firrtl-Transforms.rst
  variables.mk
Labels: changelog:removed

#1860 Remove tapeout.GenerateModelStageMain
  .github/scripts/remote-do-rtl-build.sh
  common.mk
  docs/Customization/Firrtl-Transforms.rst
  docs/Customization/index.rst
  docs/Tools/FIRRTL.rst
  tools/tapeout/src/main/scala/transforms/ExtraTransforms.scala
  tools/tapeout/src/main/scala/transforms/GenerateModelStageMain.scala
  tools/tapeout/src/main/scala/transforms/retime/Retime.scala
  tools/tapeout/src/main/scala/transforms/stage/TapeoutStage.scala
  tools/tapeout/src/main/scala/transforms/utils/FileUtils.scala
  tools/tapeout/src/main/scala/transforms/utils/LowerAnnotations.scala
  tools/tapeout/src/main/scala/transforms/utils/ProgrammaticBundle.scala
  tools/tapeout/src/main/scala/transforms/utils/YamlHelpers.scala
  variables.mk
Labels: changelog:removed

#1868 Update MultiHarnessBinders to connect differently typed ports + Ignore TLMonitors on DigitalTop scope
  generators/chipyard/src/main/scala/System.scala
  generators/chipyard/src/main/scala/harness/MultiHarnessBinders.scala
Labels: changelog:fixed
