Repository ucb-bar/chipyard, pull requests merged in 2024-05, with the labels that each got.

#1874 add sv39 fragments
  generators/chipyard/src/main/scala/config/fragments/TileFragments.scala
  generators/firechip/src/main/scala/TargetConfigs.scala
Labels: changelog:added

#1866 Detach build.sbt from firesim's build.sbt
  build.sbt
Labels: changelog:omit

#1880 Fix classpath_cache bug
  build.sbt
  common.mk
  docs/Prototyping/General.rst
  fpga/Makefile
  variables.mk
Labels: changelog:fixed

#1882 Fix clock name and macro paths for Sky130 VLSI flow
  vlsi/example-asap7.yml
  vlsi/example-design.yml
  vlsi/example-designs/sky130-commercial.yml
  vlsi/example-designs/sky130-openroad-rockettile.yml
  vlsi/example-designs/sky130-openroad.yml
  vlsi/example-designs/sky130-rocket.yml
  vlsi/example-sky130.yml
Labels: changelog:fixed

#1461 Add singleclock broadcast clockbinder
  generators/chipyard/src/main/scala/clocking/ClockBinders.scala
  generators/chipyard/src/main/scala/config/ClockingConfigs.scala
Labels: changelog:added

#1884 Add GCD IOBinders examples
  generators/chipyard/src/main/scala/config/AbstractConfig.scala
  generators/chipyard/src/main/scala/iobinders/IOBinders.scala
  generators/chipyard/src/main/scala/iobinders/Ports.scala
Labels: changelog:added
