Repository ucb-bar/chipyard, pull requests merged in 2025-03, with the labels that each got.

#2213 Add .gitignore to tests for in-tree "cmake ." builds
  tests/.gitignore
Labels: changelog:omit

#2219 small build setup edits to prevent common failures
  conda-reqs/chipyard-extended.yaml
  conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
  scripts/build-setup.sh
Labels: changelog:fixed

#2222 Remove no-dont-touch hack - this bug has been fixed in newer CIRCT
  generators/chipyard/src/main/scala/config/MMIOAcceleratorConfigs.scala
  generators/chipyard/src/main/scala/config/RocketConfigs.scala
  generators/chipyard/src/main/scala/config/TutorialConfigs.scala
Labels: changelog:omit

#2224 Remove HasHierarchicalBusTopology mention in doc
  docs/Advanced-Concepts/Top-Testharness.rst
Labels: changelog:changed
